### ISSUE TITLE
Automatically insert snippets to the snippet file

### ISSUE THREAD

**Issue by ajsaraujo** [wenfangdu/vscode-snippet-generator#4]
First of all, kudos for making this extension, it works like a charm. 

However, I think it would be even greater if it automatically updated the snippets configuration file, rather than having the snippet copied to the user's clipboard and then expecting him/her to paste it on the snippets file. 

Do you think this is doable? I never developed a VSCode extension, nor do I know the capabilities of VSCode's API. 

If it is, I would be glad to give it a try.

**Comment by wenfangdu** [comment]
@ajsaraujo Thanks for the suggestion, the current design is actually intended, it gives the user more control over the snippet generation process, to elaborate:

- No false or duplicate snippet generation.
- If the user knows where to add the snippets, they'll have no issue editing or removing them, since the modifications are done in the same place.
- Less likely to break due to VSCode changes.

Therefore, the design will remain for the time being.
